# Create a program that will play the “cows and bulls” game with the user. The game works like this:

# Randomly generate a 4-digit number. Ask the user to guess a 4-digit number.
# For every digit that the user guessed correctly in the correct place, they have a “cow”.
# For every digit the user guessed correctly in the wrong place is a “bull.”
# Every time the user makes a guess, tell them how many “cows” and “bulls” they have.
# Once the user guesses the correct number, the game is over.
# Keep track of the number of guesses the user makes throughout teh game and tell the user at the end.

# Say the number generated by the computer is 1038. An example interaction could look like this:

#   Welcome to the Cows and Bulls Game!
#   Enter a number:
#   >>> 1234
#   2 cows, 0 bulls
#   >>> 1256
#   1 cow, 1 bull
#   ...
# Until the user guesses the number.

from random import randint


def all_indexes(iterable, element):
    index_list = []
    index = 0
    for x in iterable:
        if x == element:
            index_list.append(index)
        index += 1
    return index_list


def cows_and_bulls(digits, check):
    cows = 0
    bulls = 0
    for digit in check:
        if digit in digits:
            if all_indexes(digits, digit) == all_indexes(check, digit):
                list_1 = all_indexes(digits, digit)
                cows += len(list_1)
            else:
                list_1 = all_indexes(digits, digit)
                list_2 = all_indexes(check, digit)
                for x in list_1:
                    step = 0
                    if x == list_2[step]:
                        cows += 1
                        step += 1
                    else:
                        bulls += 1
                        step += 1
    print(f"You have {cows} cows and {bulls} bulls")


random_digits = ""
for x in range(1, 5):
    digit = randint(0, 9)
    random_digits += str(digit)

user_choice = ''
while user_choice != random_digits:
    print(random_digits)
    user_choice = input("Try to guess 4 digit number: ")
    cows_and_bulls(random_digits, user_choice)
else:
    print("You've guessed it!")
