# Create a program that will play the “cows and bulls” game with the user. The game works like this:

# Randomly generate a 4-digit number. Ask the user to guess a 4-digit number.
# For every digit that the user guessed correctly in the correct place, they have a “cow”.
# For every digit the user guessed correctly in the wrong place is a “bull.”
# Every time the user makes a guess, tell them how many “cows” and “bulls” they have.
# Once the user guesses the correct number, the game is over.
# Keep track of the number of guesses the user makes throughout teh game and tell the user at the end.

# Say the number generated by the computer is 1038. An example interaction could look like this:

#   Welcome to the Cows and Bulls Game!
#   Enter a number:
#   >>> 1234
#   2 cows, 0 bulls
#   >>> 1256
#   1 cow, 1 bull
#   ...
# Until the user guesses the number.
from random import randint


def index_collection(iterable):
    tuples = []
    step = -1
    for x in iterable:
        pair = (x, step + 1)
        tuples.append(pair)
        step += 1
    return tuples


random_digits = ''
for x in range(1, 5):
    random_digits += str(randint(0, 9))
print(random_digits)

program_index_list = index_collection(random_digits)


while True:
    cows = 0
    bulls = 0
    user_choice = input("Try to guess 4 digit number: ")
    user_index_list = index_collection(user_choice)
    for x in range(0, len(random_digits)):
        touple = user_index_list[x]
        if user_index_list[x] == program_index_list[x]:
            cows += 1
        elif touple[0] in random_digits:
            bulls += 1
    if cows == 4:
        print("Well done! Yo've guessed all the digits!")
        break
    else:
        print(f'You have {cows} cows and {bulls} bulls, try again')
